package com.sistema.financiero.persistencia;
// Generated 3/06/2018 01:35:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="sistemafinanciero"
)
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private String nombres;
     private String apellidos;
     private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);

    public Cliente() {
    }

	
    public Cliente(ClienteId id, String nombres, String apellidos) {
        this.id = id;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Cliente(ClienteId id, String nombres, String apellidos, Set<Tarjeta> tarjetas) {
       this.id = id;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tarjetas = tarjetas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tipoId", column=@Column(name="TIPO_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, length=20) ) } )
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }

    
    @Column(name="NOMBRES", nullable=false, length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="APELLIDOS", nullable=false, length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Tarjeta> getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set<Tarjeta> tarjetas) {
        this.tarjetas = tarjetas;
    }




}


