package com.sistema.financiero.persistencia;
// Generated 3/06/2018 01:35:04 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="sistemafinanciero"
)
public class Compra  implements java.io.Serializable {


     private CompraId id;
     private Tarjeta tarjeta;
     private String compra;
     private int precioCompra;
     private String estado;

    public Compra() {
    }

    public Compra(CompraId id, Tarjeta tarjeta, String compra, int precioCompra, String estado) {
       this.id = id;
       this.tarjeta = tarjeta;
       this.compra = compra;
       this.precioCompra = precioCompra;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numeroTarjeta", column=@Column(name="NUMERO_TARJETA", nullable=false, length=20) ), 
        @AttributeOverride(name="fecha", column=@Column(name="FECHA", nullable=false, length=19) ) } )
    public CompraId getId() {
        return this.id;
    }
    
    public void setId(CompraId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUMERO_TARJETA", nullable=false, insertable=false, updatable=false)
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="COMPRA", nullable=false, length=200)
    public String getCompra() {
        return this.compra;
    }
    
    public void setCompra(String compra) {
        this.compra = compra;
    }

    
    @Column(name="PRECIO_COMPRA", nullable=false)
    public int getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(int precioCompra) {
        this.precioCompra = precioCompra;
    }

    
    @Column(name="ESTADO", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


