package com.sistema.financiero.persistencia;
// Generated 3/06/2018 01:35:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompraId generated by hbm2java
 */
@Embeddable
public class CompraId  implements java.io.Serializable {


     private String numeroTarjeta;
     private Date fecha;

    public CompraId() {
    }

    public CompraId(String numeroTarjeta, Date fecha) {
       this.numeroTarjeta = numeroTarjeta;
       this.fecha = fecha;
    }
   


    @Column(name="NUMERO_TARJETA", nullable=false, length=20)
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }


    @Column(name="FECHA", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompraId) ) return false;
		 CompraId castOther = ( CompraId ) other; 
         
		 return ( (this.getNumeroTarjeta()==castOther.getNumeroTarjeta()) || ( this.getNumeroTarjeta()!=null && castOther.getNumeroTarjeta()!=null && this.getNumeroTarjeta().equals(castOther.getNumeroTarjeta()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumeroTarjeta() == null ? 0 : this.getNumeroTarjeta().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


