package com.sistema.financiero.persistencia;
// Generated 3/06/2018 01:35:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name="tarjeta"
    ,catalog="sistemafinanciero"
)
public class Tarjeta  implements java.io.Serializable {


     private String numeroTarjeta;
     private Cliente cliente;
     private int cupo;
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Tarjeta() {
    }

	
    public Tarjeta(String numeroTarjeta, Cliente cliente, int cupo) {
        this.numeroTarjeta = numeroTarjeta;
        this.cliente = cliente;
        this.cupo = cupo;
    }
    public Tarjeta(String numeroTarjeta, Cliente cliente, int cupo, Set<Compra> compras) {
       this.numeroTarjeta = numeroTarjeta;
       this.cliente = cliente;
       this.cupo = cupo;
       this.compras = compras;
    }
   
     @Id 

    
    @Column(name="NUMERO_TARJETA", unique=true, nullable=false, length=20)
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="TIPO_ID", referencedColumnName="TIPO_ID", nullable=false), 
        @JoinColumn(name="ID", referencedColumnName="ID", nullable=false) } )
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="CUPO", nullable=false)
    public int getCupo() {
        return this.cupo;
    }
    
    public void setCupo(int cupo) {
        this.cupo = cupo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarjeta")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


